BBBB BBBBBBBBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXXX
    XXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXX XX XXX XXXXXXXXX XXXXX XXX XXX XXX X XXXXXXX XXXXXX XXXXXXXXXXXX XXXXX XX XXXXX XX XXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXX XXXXXXX XXX XXXXXX XXXX XXX XXXX XXXXXXXXXX XXX XXXXX XXXXXXXX XXX XX XXXX XXX XXXXXX XXX XX XXXXXXXX XX XXX XXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

XXXX XXXXXXXXXXXXX
    XXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXX XX  XXXXXXXX XX XXXXX XXXX XXXXXXXX XXXX XXXX XXXXXXXXX
                                 XXX XX XXX XXXXXX XXXX XX XXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXXXXXXX XXXXXXXXXX X XXXXXXXX  XXXXXXX XXXXXXXXX
                                XXXXX XXXXXXXXXXX XX XXXXX  XXXXXX XXX XXXXXXX XXXXXXX XXXX
                        XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXX XXXXXXXX XXXX XXXX XX XXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

