BBBB BBBBBBBBBBB BBBBBBBBBB

XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXX XXXX XXXX XXX XXXXXXXXXX XXXX X XXXXXX X XXX XXXX XX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    X XXX XXXXXXXX XXXXX XXXX XXX XXXX XXXXX XX X XXXXXXXXX XXXXXX XXXX
                XXX XXX XXXXXXXXXX XXX XXXX XXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXX XXXXXX XXX XXXXXXXXXXXXXXXXXX XXXX
                XXX X XXXXXXXX XXXXXXXX XX XX XXXXX XX XXXXXX XXX XXXXXXXX XXXXXXXX XXXX XXXXXXXXX
                    XXX XXXX XXXX XXX XXXX XX XXX XXXX XXX XXXX XXX XXXX XXXX XX X XXXXXXX XXXXXXX
                    XX XXX XXXXX XX XXXX XXXX XXX XXXX XXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                    XXXXX XXXX XX XXXXX XX XXXX XXXXXXX XXXXXXXX XXXX
                XXX XXX XXXXX XXXXX XXXXXXXXXX XXX XXXXXX XX X XXXXXXX XXXXX XXXX
            XXXXXX
            XX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
    BBBB BBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
    BBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
    BBBBB
            XXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX XXXX XXX XXXXXX XX XXXX XX XXX XXXXXXXX XXXX XXXXXXXXXX XXX XXXXXXXXX
            XXXXXX
        XXXXXX
XXXXXX



