BBBB BBBBBBBBBBB BBBBBBBBBB
XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
        BB BBB BBBBBBBBBBBBBBBBBBBB

XX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXX XXXXXXXXXXXXXXXXXX

           XXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XX X XXXXX XXX XXXX XX XXX XXX XXXXXXXXXXXX XXXXXX
        XXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXX

        BBBB BBBBBBBBBBBBBBBBBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBB BB B
                XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
            BBBB BBBBBBBBBBBBBBBBBBBBBBB BB B
                XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
            BBBB
                XXXX XXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
            BBBBB
                XXXX XXXXXXXXXXXXXXXX
                XXXX
                XXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                XX XXXXXXXX XXX X XXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXX  XXX XXXXXXXXXXXXX XXXXXXX XXXX XXXX XX XXXX XXXXXX XX XXXX XX X XXXXXX

        BBBBB

      XXXXXX
    XXXXXX

XXXXXX
XXXXXX